/* ── ZGROUP Product Catalog (55 items) ── */
const CATALOG = [
  {id:'EST-001',code:'EST-001',name:'ZGROUP STORE XL - IZQUIERDA',cat:'Trab. Estructura',tipo:'ACTIVO',unit:'und',price:5900,detalle:'CAJA ISOTERMICA DE 40 PIES CON LUMINARIAS Y PISO PLANO'},
  {id:'EST-002',code:'EST-002',name:'ZGROUP STORE XL - DERECHA',cat:'Trab. Estructura',tipo:'ACTIVO',unit:'und',price:5900,detalle:'CAJA ISOTERMICA DE 40 PIES CON LUMINARIAS Y PISO PLANO'},
  {id:'EST-003',code:'EST-003',name:'ZGROUP STORE XL - MEDIA',cat:'Trab. Estructura',tipo:'ACTIVO',unit:'und',price:6900,detalle:'CAJA ISOTERMICA DE 40 PIES CON LUMINARIAS Y PISO PLANO'},
  {id:'EST-004',code:'EST-004',name:'CAJA ISOTERMICA 40 RH',cat:'Trab. Estructura',tipo:'ACTIVO',unit:'und',price:4500,detalle:'CAJA ISOTERMICA DE 40 PIES'},
  {id:'EST-005',code:'EST-005',name:'REDUCCION CAJA ISOTERMICA A MEDIDA',cat:'Trab. Estructura',tipo:'CONSUMIBLE',unit:'und',price:1100,detalle:''},
  {id:'EST-006',code:'EST-006',name:'EXTENSION CAJA ISOTERMICA A MEDIDA',cat:'Trab. Estructura',tipo:'CONSUMIBLE',unit:'und',price:1100,detalle:''},
  {id:'EST-007',code:'EST-007',name:'ABRIR BOCA',cat:'Trab. Estructura',tipo:'CONSUMIBLE',unit:'und',price:1100,detalle:'ABRIR DEL LADO DE LA MAQUINA'},
  {id:'EST-008',code:'EST-008',name:'PANEL DIVISION',cat:'Trab. Estructura',tipo:'ACTIVO',unit:'und',price:1100,detalle:'2300MM X 2590MM'},
  {id:'EST-009',code:'EST-009',name:'PANEL DIVISION PARA PB 1,50*2,45',cat:'Trab. Estructura',tipo:'ACTIVO',unit:'und',price:375,detalle:'TOTAL DE PANEL 0,80 M x 2,59 M'},
  {id:'EST-010',code:'EST-010',name:'PISO PLANO 40 RH',cat:'Trab. Estructura',tipo:'ACTIVO',unit:'und',price:1000,detalle:''},
  {id:'EST-011',code:'EST-011',name:'PISO PLANO 20 RH',cat:'Trab. Estructura',tipo:'CONSUMIBLE',unit:'und',price:900,detalle:''},
  {id:'EST-012',code:'EST-012',name:'CORTE PANEL POR METRO',cat:'Trab. Estructura',tipo:'CONSUMIBLE',unit:'ml',price:290,detalle:''},
  {id:'EST-013',code:'EST-013',name:'APERTURA LATERAL PUERTAS',cat:'Trab. Estructura',tipo:'CONSUMIBLE',unit:'und',price:500,detalle:'EN CASO DE XL'},
  {id:'EST-014',code:'EST-014',name:'MARCO MAQUINA',cat:'Trab. Estructura',tipo:'ACTIVO',unit:'und',price:750,detalle:''},
  {id:'EST-015',code:'EST-015',name:'TAPA PANEL',cat:'Trab. Estructura',tipo:'ACTIVO',unit:'und',price:1000,detalle:''},
  {id:'EST-016',code:'EST-016',name:'CORTE TECHO CONTENEDORES 1er NIVEL',cat:'Trab. Estructura',tipo:'CONSUMIBLE',unit:'und',price:750,detalle:'POR CADA CONTENEDOR'},
  {id:'EST-017',code:'EST-017',name:'CORTE PISO CONTENEDORES 2do NIVEL',cat:'Trab. Estructura',tipo:'CONSUMIBLE',unit:'und',price:750,detalle:'POR CADA CONTENEDOR'},
  {id:'EST-018',code:'EST-018',name:'COLUMNA SOPORTE PARA SEGUNDO PISO',cat:'Trab. Estructura',tipo:'ACTIVO',unit:'und',price:1490,detalle:'POR CADA COLUMNA'},
  {id:'EST-019',code:'EST-019',name:'SELLADO UNION 1er Y 2do NIVEL',cat:'Trab. Estructura',tipo:'CONSUMIBLE',unit:'und',price:1000,detalle:'POR CADA CONTENEDOR'},
  {id:'EST-020',code:'EST-020',name:'REFUERZO DE PISO PARA MONTACARGAS',cat:'Trab. Estructura',tipo:'ACTIVO',unit:'und',price:890,detalle:'POR CONTENEDOR'},
  {id:'EST-021',code:'EST-021',name:'SKID PARA CONTENEDORES',cat:'Trab. Estructura',tipo:'ACTIVO',unit:'und',price:6900,detalle:'POR CADA 2XL'},
  {id:'FRI-001',code:'FRI-001',name:'MAQUINA REEFER SEGUNDO USO',cat:'Sistema de Frio',tipo:'ACTIVO',unit:'und',price:4900,detalle:''},
  {id:'FRI-002',code:'FRI-002',name:'MAQUINA REEFER MAGNUM PLUS MP4000',cat:'Sistema de Frio',tipo:'ACTIVO',unit:'und',price:11900,detalle:'6 AÑOS DE GARANTIA'},
  {id:'FRI-003',code:'FRI-003',name:'MAQUINA REEFER MAGNUM PLUS MP5000',cat:'Sistema de Frio',tipo:'ACTIVO',unit:'und',price:13090,detalle:'10 AÑOS DE GARANTIA'},
  {id:'FRI-004',code:'FRI-004',name:'DOOR AFAM - SEGUNDO USO',cat:'Sistema de Frio',tipo:'ACTIVO',unit:'und',price:280,detalle:''},
  {id:'FRI-005',code:'FRI-005',name:'ACTUATOR - SEGUNDO USO',cat:'Sistema de Frio',tipo:'ACTIVO',unit:'und',price:1101,detalle:''},
  {id:'FRI-006',code:'FRI-006',name:'SISTEMA DE MADURACIÓN',cat:'Sistema de Frio',tipo:'ACTIVO',unit:'glb',price:8600,detalle:''},
  {id:'FRI-007',code:'FRI-007',name:'SISTEMA DE HUMIDIFICACIÓN',cat:'Sistema de Frio',tipo:'ACTIVO',unit:'glb',price:2500,detalle:'HUMIDIFICADOR ULTRASONIDO + TANQUE + TARJETA CONTROL'},
  {id:'FRI-008',code:'FRI-008',name:'SISTEMA BICAMARA',cat:'Sistema de Frio',tipo:'ACTIVO',unit:'glb',price:2900,detalle:''},
  {id:'ACC-001',code:'ACC-001',name:'LUMINARIA',cat:'Accesorios',tipo:'ACTIVO',unit:'und',price:390,detalle:''},
  {id:'ACC-002',code:'ACC-002',name:'ALARMA',cat:'Accesorios',tipo:'ACTIVO',unit:'und',price:180,detalle:''},
  {id:'ACC-003',code:'ACC-003',name:'SOPORTE REGULABLE',cat:'Accesorios',tipo:'CONSUMIBLE',unit:'und',price:450,detalle:''},
  {id:'ACC-004',code:'ACC-004',name:'CORTINA 1500MM X 2200MM',cat:'Accesorios',tipo:'CONSUMIBLE',unit:'und',price:200,detalle:''},
  {id:'ACC-005',code:'ACC-005',name:'CORTINA 1500MM X 2450MM',cat:'Accesorios',tipo:'CONSUMIBLE',unit:'und',price:250,detalle:''},
  {id:'ACC-006',code:'ACC-006',name:'CORTINA 2300MM X 2500MM',cat:'Accesorios',tipo:'CONSUMIBLE',unit:'und',price:300,detalle:''},
  {id:'ACC-007',code:'ACC-007',name:'MODULO DE CARGA',cat:'Accesorios',tipo:'ACTIVO',unit:'und',price:13990,detalle:'INCL. ENCUESTO + RAMPA + LUMINARIA + INTERRUPTOR + 2 TOPES'},
  {id:'ACC-008',code:'ACC-008',name:'ENCUESTO INFLABLE',cat:'Accesorios',tipo:'ACTIVO',unit:'und',price:4000,detalle:''},
  {id:'ACC-009',code:'ACC-009',name:'RAMPAS HIDRAULICAS',cat:'Accesorios',tipo:'ACTIVO',unit:'und',price:3600,detalle:''},
  {id:'ACC-010',code:'ACC-010',name:'ABRIGO RETRACTIL (FLEX)',cat:'Accesorios',tipo:'ACTIVO',unit:'und',price:1500,detalle:''},
  {id:'ACC-011',code:'ACC-011',name:'RAMPA ACERO AL CARBONO 1.50 X 2.00 M',cat:'Accesorios',tipo:'ACTIVO',unit:'und',price:590,detalle:''},
  {id:'ACC-012',code:'ACC-012',name:'PROTECCION MUELLE',cat:'Accesorios',tipo:'ACTIVO',unit:'und',price:2000,detalle:''},
  {id:'ACC-013',code:'ACC-013',name:'CORTINAS DE AIRE 1500MM',cat:'Accesorios',tipo:'ACTIVO',unit:'und',price:1100,detalle:'1500MM DE ANCHO'},
  {id:'ACC-014',code:'ACC-014',name:'EXTENSION CHASIS + EJES SISTEMA COMPLETO',cat:'Accesorios',tipo:'ACTIVO',unit:'und',price:3706,detalle:'NO INCLUYE LLANTAS Y AROS'},
  {id:'ACC-015',code:'ACC-015',name:'UNION PLEGABLE PARA XL',cat:'Accesorios',tipo:'CONSUMIBLE',unit:'ml',price:1500,detalle:'POR LINEA'},
  {id:'ACC-016',code:'ACC-016',name:'COLCHONETAS PARA PUERTA SECCIONAL',cat:'Accesorios',tipo:'CONSUMIBLE',unit:'und',price:900,detalle:''},
  {id:'ACC-017',code:'ACC-017',name:'CORTINA ENROLLABLE 1.70m X 2.50m',cat:'Accesorios',tipo:'CONSUMIBLE',unit:'und',price:505,detalle:''},
  {id:'ACC-018',code:'ACC-018',name:'KIT COLCHONETAS + CORTINA ENROLLABLE',cat:'Accesorios',tipo:'CONSUMIBLE',unit:'kit',price:850,detalle:'PARA BOCAS DE BLAST FREEZER'},
  {id:'PTA-001',code:'PTA-001',name:'PUERTA BATIENTE 1000MM X 2200MM',cat:'Puertas',tipo:'ACTIVO',unit:'und',price:1590,detalle:'ESPESOR PANEL 100MM'},
  {id:'PTA-002',code:'PTA-002',name:'PUERTA BATIENTE 1500MM X 2200MM',cat:'Puertas',tipo:'ACTIVO',unit:'und',price:2200,detalle:'ESPESOR PANEL 100MM'},
  {id:'PTA-003',code:'PTA-003',name:'PUERTA BATIENTE 1500MM X 2450MM',cat:'Puertas',tipo:'ACTIVO',unit:'und',price:2300,detalle:'ESPESOR PANEL 100MM'},
  {id:'PTA-004',code:'PTA-004',name:'PUERTA CORREDERA 1000MM X 2200MM',cat:'Puertas',tipo:'ACTIVO',unit:'und',price:2300,detalle:'ESPESOR PANEL 100MM'},
  {id:'PTA-005',code:'PTA-005',name:'PUERTA CORREDERA 1500MM X 2200MM',cat:'Puertas',tipo:'ACTIVO',unit:'und',price:2300,detalle:'ESPESOR PANEL 100MM'},
  {id:'PTA-006',code:'PTA-006',name:'PUERTA CORREDERA 2700MM X 2450MM',cat:'Puertas',tipo:'ACTIVO',unit:'und',price:3000,detalle:'ESPESOR PANEL 100MM'},
  {id:'PTA-007',code:'PTA-007',name:'PUERTA SECCIONAL 2300MM X 2500MM',cat:'Puertas',tipo:'ACTIVO',unit:'und',price:2600,detalle:'ESPESOR PANEL 40MM'},
  {id:'PTA-008',code:'PTA-008',name:'HIGH SPEED ROLL UP DOOR 2300MM X 2500MM',cat:'Puertas',tipo:'ACTIVO',unit:'und',price:3900,detalle:'DE MANTA ELECT'},
];

const CATEGORIES = ['Todos','Trab. Estructura','Sistema de Frio','Accesorios','Puertas'];
